### PR TITLE
#80 GDPR option to check cookie value for cookie group setting

### PR DESCRIPTION
**Pull request by GaryHaddon**

### CODE REVIEW

**Comment by srenon** [comment]
@GaryHaddon, thanks for the for the contribution.
Could you provide a sample allowedCookieGroupSettings = JSON.parse(cookieGroupSettings);?

**Comment by GaryHaddon** [comment]
Hi i added an the example from the issue i created below. Let me know if you would like more info

image

**Comment by GaryHaddon** [comment]
@srenon I have reviewed a few use cases to this and am going to rewrite it to support more use cases I think we need to support combinations of the following. As some cookie modules have a combination of cookies allowed in an array (with or without a true false flag) they also then set a different value if all cookies are accepted. 

"cookies allowed": {"marketing":1,"performance":0}

"cookies allowed": {"marketing","performance"}

"cookies allowed": "all"

"cookies allowed": {"all"}

We should also probably support the inverse too for opt out scenarios.

"cookies rejected": {"marketing":1,"performance":0}

"cookies rejected": {"marketing","performance"}

"cookies rejected": "all"

"cookies rejected": {"all"}

Please let me know your thoughts

Thanks

**Comment by GaryHaddon** [comment]
Closing as solution above isn't sufficient.

**Pull request closed without merging**
