### PR TITLE
GDPR Compliance

### PR DESCRIPTION
**Pull request by simonmaass**
we added this little code in order to be gdpr compliante... and only load the GTM if the user accepted the cookies..

### CODE REVIEW

**Comment by srenon** [comment]
@simonmaass .... not sure why you close the PR but I'm already in the process of adding similar functionality. However, I will add the ability for the store owner to choose if they want to include the GTM code in the header or load it using JS which could be few milli-seconds slow and affect page loading status

**Comment by simonmaass** [comment]
@srenon sorry - that was a missclick...

**Comment by srenon** [comment]
@simonmaass.. Thanks for the PR, I release a new version with some of your code. The merge conflict would have taken too long resolve so it was easier to cut and paste logic as need.

Thanks.

**Comment by simonmaass** [comment]
great to know :)!

**Pull request closed without merging**
