### PR TITLE
Fix issue when HTML minify is enabled

### PR DESCRIPTION
**Pull request by magefan**
When HTML is enabled magento not correctly minify .phtml files whit // characters

### CODE REVIEW

**Comment by srenon** [comment]
@magefan ... I'm working on multiple page speed improvement on various M2.2 and M2.19 and did not run into this issue. What version of Magento are you using?

Magento EE 2.1.9 with Minify Enabled

image

Core M2.2.2 with default Minify enabled, plus a new minifier module I'm working on 

image

**Comment by magefan** [comment]
This issue was detected on 
Magneto  2.1.8
Production mode: ON
Minify Html: YES

**Comment by magefan** [comment]
Magento has a similar problem with the comments "//"
https://github.com/magento/magento2/issues/5316

**Comment by magefan** [comment]
All our clients what use Magepal GTM extension gets 404 errors like http://domain.com/foo/height= in google search console.
This is due to this issue. The iframe is broken. 
image

This pull request is very important for us. Could you add this fix and release a new version?

**Comment by srenon** [comment]
@magefan .... done ... but I can not replicate this issue with similar settings

**Comment by magefan** [comment]
Thank you very much!

**Pull request merged**
